### ISSUE TITLE
Latest versions include a lot of extra .dlls.  Is this intentional?

### ISSUE THREAD

**Issue by ZenDragonX** [modestimpala/OdinOnDemand#17]
I noticed the latest version has a lot of extra .dlls included after v0.9.951.  Is this intentional or were they included by accident?

**Comment by modestimpala** [comment]
Yes, this is intentional. 

Thunderstore implemented some sort of automatic review for mods recently. I used a library called Costura.Fody to bundle all my other libraries together into the single OdinOnDemand DLL. Unfortunately this is done through dynamic assembly loading which pops thunderstores automatic review and removes my mod every time I upload it. I had to practically rip the answer out of the mods hands to figure out what was causing it. Other than having more visible DLL files everything is the same library wise.

**Comment by modestimpala** [comment]
@ZenDragonX  Just as an extra note, I do plan on merging these DLLs for the next release, I just really wanted to avoid having to go into their discord and wait for a mod to approve my mod. 

Also, I opened up the discussions section for this repo. Feel free to contribute anything you'd like to that section and then this area can be used for bugs/issues and enhancements. I find I'm a little heavy handed closing issues but I just like things to be clean.
Thanks for the question!
