### ISSUE TITLE
Would love to have this updated, even without YouTube functions!

### ISSUE THREAD

**Issue by Stonedprophet** [modestimpala/OdinOnDemand#30]
Greetings!  I tried reaching out in the Nexus page comments but maybe this is a better way to reach you.  I'll just paste what I wrote there so there's no confusion:

So, obviously the Bog Witch update has dropped and mods are being patched slowly from the mod devs.  Do you think you’ll be patching this mod anytime soon?  Even without it’s YouTube connectivity, we are making use of it. 

we will actually be featuring the use of this mod quite a bit in a large scale event planned by a few communities.  If any donations or contributions would help keep this mod compatible with the latest build of Valheim, please let me know personally.  It’s a valuable and unique mod and we want to show it off to a wider audience!  

no matter what, we always appreciate the effort of all you mod developers!  You all deserve to be recognized

**Comment by modestimpala** [comment]
Hi StonedProphet, I really appreciate the continued support and enthusiasm towards the project.

Apologies for the delay. I have been quite busy. I wasn't aware of the new update until recently, but I will be releasing a patch for this soon. 

I'm working on a few tests for YouTube to see if it's still possible and then I'll have the patch out as soon as I can. Expect a Bog Witch compatibility patch at the very least within a day or two. 
No monetary donations required, which is very kind of you to offer. I'm sorry that the plugin has been a bit neglected lately, by both YouTube and myself. I've moved on to Unreal Engine work lately so that has been consuming my free time.

Regards,
Moddy

**Comment by modestimpala** [comment]
See 1.0.8:

> ## 1.0.8
>  - Supplemented broken YouTubeExplode commands with YoutubeDLSharp
> 	- As a side effect, you can now grab videos from a wide variety of sites: vimeo, TikTok, dailymotion, facebook, Instagram, twitter, reddit, etc. Just try your site of choice and it may return a valid file.
> 	- On the flip side, YouTube videos are now limited to 360p due to scarce muxed video options 
>  - Fixed SoundcloudExplode 401 errors
>  - Fixed PlacePiecePatch

**Comment by Stonedprophet** [comment]
My friend, I really want to thank you.  Those people like you who continue to update and improve their mods is a great part of Valheim's continued success.  We are hosting an large-scale event in Feb of next year.  It will be made public soon and part of our goal is to spotlight positive contributors like yourself.  THANK YOU!
